/*
-- Query: SELECT * FROM flight.users
LIMIT 0, 1000

-- Date: 2016-07-19 15:19
*/
INSERT INTO `users` (`username`,`password`,`first`,`last`,`email`,`gender`,`dob`,`mob`,`passport`,`line1`,`line2`,`state`,`city`,`zip`,`ctype`,`cno`,`cval`,`code`,`utype`,`ques`,`answer`) VALUES ('admin','admin','n','n','n','n','n','n','n','n','n','n','n','n','n','n','n','n',1,0,'golu');
INSERT INTO `users` (`username`,`password`,`first`,`last`,`email`,`gender`,`dob`,`mob`,`passport`,`line1`,`line2`,`state`,`city`,`zip`,`ctype`,`cno`,`cval`,`code`,`utype`,`ques`,`answer`) VALUES ('ballu','qwer','Balwendra','Singh','vcja@mail/com','Male','25 August 2005','9887654092','qwe1236g9','4 Beagle Road','Maqbool Ganj','Uttar Pradesh','Barabanki','345789',NULL,NULL,NULL,NULL,0,0,'polu');
INSERT INTO `users` (`username`,`password`,`first`,`last`,`email`,`gender`,`dob`,`mob`,`passport`,`line1`,`line2`,`state`,`city`,`zip`,`ctype`,`cno`,`cval`,`code`,`utype`,`ques`,`answer`) VALUES ('damb','2345','Sultan','Khan','hvhg@gmail.com','Male','4 April 1995','1234567890','RTY54U75B','10 Sahu nagar','Khao Gali near post Office','Uttar Pradesh','Jaunpur','123498','D','8967452313254761','12/02/2033','GT4',0,0,'tolu');
INSERT INTO `users` (`username`,`password`,`first`,`last`,`email`,`gender`,`dob`,`mob`,`passport`,`line1`,`line2`,`state`,`city`,`zip`,`ctype`,`cno`,`cval`,`code`,`utype`,`ques`,`answer`) VALUES ('damn','zxc','Raj','Khurana','jsdbv@bkvs.com','Male','26 September 1993','9883576509','FGTR32178','23 Gokhle Marg','New Horizon Colony','Uttar Pradesh','Kanpur','234587',NULL,NULL,NULL,NULL,0,0,'qolu');
INSERT INTO `users` (`username`,`password`,`first`,`last`,`email`,`gender`,`dob`,`mob`,`passport`,`line1`,`line2`,`state`,`city`,`zip`,`ctype`,`cno`,`cval`,`code`,`utype`,`ques`,`answer`) VALUES ('faisal','2345','Mohammed','Faisal','faisal.09md@gmail.com','male','9 October 1995','7071779589','123H4V8N6','8/1A, Sarvapalli Mall Avenue','Lucknow','Uttar Pradesh','Lucknow','226001','D','1234567891234567','13/08/2033','F43',0,0,'pipu');
INSERT INTO `users` (`username`,`password`,`first`,`last`,`email`,`gender`,`dob`,`mob`,`passport`,`line1`,`line2`,`state`,`city`,`zip`,`ctype`,`cno`,`cval`,`code`,`utype`,`ques`,`answer`) VALUES ('lastsamurai','zxcv','Samurai','Jack','jdvaj@khdbjh.com','Male','6 November 1950','4563926540','TYV453NI8','65 Park Lane','Trans Ganga colony','Uttar Pradesh','Kanpur','243687',NULL,NULL,NULL,NULL,0,0,'mipu');
INSERT INTO `users` (`username`,`password`,`first`,`last`,`email`,`gender`,`dob`,`mob`,`passport`,`line1`,`line2`,`state`,`city`,`zip`,`ctype`,`cno`,`cval`,`code`,`utype`,`ques`,`answer`) VALUES ('lola','mnbv','Bhavna','Singhal','hjjg@gmail.com','Male','30 May 1993','8966464984','GTYEIOP34','10 Butcher Colony','Avas Vikas','Uttar Pradesh','Muzaffarnagar','456372',NULL,NULL,NULL,NULL,0,0,'tipu');
INSERT INTO `users` (`username`,`password`,`first`,`last`,`email`,`gender`,`dob`,`mob`,`passport`,`line1`,`line2`,`state`,`city`,`zip`,`ctype`,`cno`,`cval`,`code`,`utype`,`ques`,`answer`) VALUES ('wader','wader','Darth','Wader','hvv@gmail.com','Male','7 April 1990','4474667397','BHF45G64G','vvkvu ycyv ycy','hvuv gvy','Uttar Pradesh','Lucknow','768844',NULL,NULL,NULL,NULL,0,1,'Lucknow');
